# Generated by Django 4.2.15 on 2024-08-31 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanage', '0002_author_book_library_member_publisher_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarymanage.author'),
        ),
    ]
